// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Snippet struct {
	ID    string `json:"_id"`
	Text  string `json:"text"`
	Title string `json:"title"`
}

type SnippetInput struct {
	Text  string `json:"text"`
	Title string `json:"title"`
}
